language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

install:
  - pip install coverage coveralls

script:
  - coverage run --branch -m unittest discover -s saga -p "*_test.py"

after_success:
  - coveralls
